# Generated by Django 5.1.6 on 2025-03-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(db_index=True, max_length=50)),
                ('position', models.FloatField(db_index=True, unique=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
