# Generated by Django 5.1.6 on 2025-03-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
