# Generated by Django 5.1.6 on 2025-03-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_color_alter_car_name_alter_car_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.FloatField(),
        ),
    ]
